config/routes.rb
Rails.application.routes.draw do

  resources :psicologos do
    member do
      get 'agenda', to: 'psicologos#main'
    end
    resources :pacientes
    resources :sessaos
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'landing', to: 'sessions#landing'
  delete 'logout', to: 'sessions#destroy'
  root 'sessions#landing'

end

app/models/paciente.rb
class Paciente < ApplicationRecord
  validates :nome, presence: true, length: {minimum: 3}
  validates :cpf, presence: true, length: {minimum: 11}, uniqueness: true
  validates :telefone, presence: true, length: {minimum: 11}
  VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :email, presence: true, length: {minimum: 5}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
  validates :endereco, presence: true, length: {minimum: 10}
  validates :estado_civil, presence: true, length: {minimum: 5}
  validates :quant_filhos, presence: true
  validates :eh_fumante, presence: true
  validates :ingere_alcool, presence: true
  belongs_to :psicologo
  has_many :sessaos, dependent: :destroy
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :get_psicologo
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]
  helper_method :usuario_autorizado?

  # GET /pacientes
  # GET /pacientes.json
  def index
    @pacientes = @psicologo.pacientes
    unless @pacientes[0].nil?
      unless @pacientes[0].psicologo_id == session[:user_id]
        redirect_to agenda_psicologo_path(usuario_atual)
      end
    end

  end


  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
    redirect_to agenda_psicologo_path(usuario_atual) unless usuario_autorizado?
    return 
  end

  # GET /pacientes/new
  def new
    @paciente = @psicologo.pacientes.build
  end

  # GET /pacientes/1/edit
  def edit
    redirect_to agenda_psicologo_path(usuario_atual) unless usuario_autorizado?
    return 
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @paciente = @psicologo.pacientes.build(
    "nome" => paciente_params[:nome],
    "cpf" => paciente_params[:cpf],
    "telefone" => paciente_params[:telefone],
    "email" => paciente_params[:email],
    "endereco" => paciente_params[:endereco],
    "estado_civil" => paciente_params[:estado_civil],
    "quant_filhos" => paciente_params[:quant_filhos],
    "historico_doencas" => paciente_params[:historico_doencas],
    "medicamentos" => paciente_params[:medicamentos],
    "eh_fumante" => paciente_params[:eh_fumante],
    "ingere_alcool" => paciente_params[:ingere_alcool],
    "psicologo_id" => session[:user_id]
    )

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to psicologo_pacientes_path(@psicologo, @paciente), notice: 'Paciente was successfully created.' }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  def update
    return unless usuario_autorizado?

    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to psicologo_pacientes_path(@psicologo), notice: 'Paciente was successfully updated.' }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    return unless usuario_autorizado?

    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to psicologo_pacientes_path(@psicologo), notice: 'Paciente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = @psicologo.pacientes.find(params[:id])
    end

  def get_psicologo
    @psicologo = Psicologo.find(params[:psicologo_id])
  end

  # Only allow a list of trusted parameters through.
    def paciente_params
      params.require(:paciente).permit(:nome, :cpf, :telefone, :email, :endereco, :estado_civil, :quant_filhos, :historico_doencas, :medicamentos, :eh_fumante, :ingere_alcool)
    end

    def usuario_autorizado? 
      @paciente.psicologo_id == session[:user_id]
    end
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/pacientes/_form.html.erb
<%= form_with(model: [@psicologo, paciente], local: true) do |form| %>
  <% if paciente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paciente.errors.count, "error") %> prohibited this paciente from being saved:</h2>

      <ul>
        <% paciente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco %>
  </div>

  <div class="field">
    <%= form.label :estado_civil %>
    <%= form.select :estado_civil,['Solteiro', 'Casado','Divorciado','Outros'] %>
  </div>

  <div class="field">
    <%= form.label :quant_filhos %>
    <%= form.number_field :quant_filhos, value: 0, min: 0, max: 20 %>
  </div>

  <div class="field">
    <%= form.label :historico_doencas %>
    <%= form.text_area :historico_doencas %>
  </div>

  <div class="field">
    <%= form.label :medicamentos %>
    <%= form.text_area :medicamentos %>
  </div>

  <div class="field">
    <%= form.label :eh_fumante %>
    <%= form.select :eh_fumante,['Sim', 'Não'] %>
  </div>

  <div class="field">
    <%= form.label :ingere_alcool %>
    <%= form.select :ingere_alcool,['Sim', 'Não'] %>
  </div>

  <div class="actions">
    <%= form.submit "Cadastrar", id: "criar-paciente" %>
  </div>
<% end %>

app/views/pacientes/edit.html.erb
<h1>Editing Paciente</h1>

<%= render 'form', paciente: @paciente %>

<%= link_to 'Mostrar', [@psicologo, @paciente] %> |
<%= link_to 'Voltar', psicologo_pacientes_path(@psicologo) %>

app/views/pacientes/index.html.erb
<%= stylesheet_link_tag "pacientes" %>
<p id="notice"><%= notice %></p>

<h1>Pacientes</h1>
<% if !@psicologo.pacientes.empty? %>
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Telefone</th>
      <th>Email</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pacientes.each do |paciente| %>
      <tr>
        <td><%= paciente.nome %></td>
        <td><%= paciente.cpf %></td>
        <td><%= paciente.telefone %></td>
        <td><%= paciente.email %></td>
        <td><%= link_to 'Mostrar', psicologo_paciente_path(@psicologo, paciente) %></td>
        <td><%= link_to 'Editar', edit_psicologo_paciente_path(@psicologo, paciente), id:"e-#{paciente.cpf}" %></td>
        <td><%= link_to 'Deletar', [@psicologo, paciente], id:"d-#{paciente.cpf}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Voltar', agenda_psicologo_path(usuario_atual) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%end %>
<br>

<%= link_to 'Cadastrar Novo Paciente', new_psicologo_paciente_path(@psicologo) %>
<br>
<%= link_to 'Voltar', agenda_psicologo_path(usuario_atual) %>

app/views/pacientes/new.html.erb
<h1>New Paciente</h1>

<%= render 'form', paciente: @paciente %>

<%= link_to 'Voltar', psicologo_pacientes_path(@psicologo) %>

app/views/pacientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @paciente.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @paciente.cpf %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @paciente.telefone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @paciente.email %>
</p>

<p>
  <strong>Endereço:</strong>
  <%= @paciente.endereco %>
</p>

<p>
  <strong>Estado Civil:</strong>
  <%= @paciente.estado_civil %>
</p>

<p>
  <strong>Quantidade de filhos:</strong>
  <%= @paciente.quant_filhos %>
</p>

<p>
  <strong>Histórico de doenças:</strong>
  <%= @paciente.historico_doencas %>
</p>

<p>
  <strong>Medicamentos:</strong>
  <%= @paciente.medicamentos %>
</p>

<p>
  <strong>Fuma?</strong>
  <%= @paciente.eh_fumante %>
</p>

<p>
  <strong>Bebe?</strong>
  <%= @paciente.ingere_alcool %>
</p>


<% if usuario_atual != nil %>
  <%= link_to 'Editar', edit_psicologo_paciente_path(@psicologo, @paciente) %> |
  <%= link_to 'Deletar', [@psicologo, @paciente], id:"delete", method: :delete, data: { confirm: 'Are you sure?' } %> |

<% end %>
<%= link_to 'Voltar', psicologo_pacientes_path(@psicologo) %>