config/routes.rb
Rails.application.routes.draw do

  resources :psicologos do
    member do
      get 'agenda', to: 'psicologos#main'
    end
    resources :pacientes
    resources :sessaos
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'landing', to: 'sessions#landing'
  delete 'logout', to: 'sessions#destroy'
  root 'sessions#landing'

end

app/models/psicologo.rb
class Psicologo < ApplicationRecord
  has_secure_password
  has_many :pacientes, dependent: :destroy
  validates :crp, presence: true, length: { minimum: 7, maximum: 10 }, uniqueness: true
  validates :nome, presence: true, length: { minimum: 4, maximum: 30 }
  validates :password, presence: true, length: { minimum: 6, maximum: 30 }, allow_blank: true
  has_many :sessaos, dependent: :destroy
end

app/controllers/psicologos_controller.rb
class PsicologosController < ApplicationController
  skip_before_action :autorizado, only: [:new, :create]
  helper_method :buscar_paciente
  before_action :set_psicologo, only: [:show, :edit, :update, :destroy]


  def new
    @psicologo = Psicologo.new
  end

  # GET /psicologos/1
  # GET /psicologos/1.json
  def show
    redirect_to agenda_psicologo_path(@psicologo.id) unless @psicologo.id == session[:user_id]
    return 
  end

  # GET /psicologos/1/edit
  def edit
    redirect_to agenda_psicologo_path(@psicologo.id) unless @psicologo.id == session[:user_id]
    return 
  end

  def create
    @psicologo = Psicologo.create(params.require(:psicologo).permit(:crp, :nome, :password))
    
    respond_to do |format|
      if @psicologo.id
        session[:user_id] = @psicologo.id
        format.html { redirect_to agenda_psicologo_path(@psicologo.id), notice: 'Usuário criado com sucesso!' }
      else
        format.html { render :new, notice: 'Erro' }
        format.json { render json: @psicologo.errors, status: :unprocessable_entity }
      end
    end
  end

  def self.search(search)
    unless search.nil?
      puts search
    end
  end

  def main
    @psicologo = usuario_atual
    @sessaos_dia = buscar_sessaos(params[:search], @psicologo)

  end

  def buscar_sessaos(data, psicologo)
    PsicologosController.search(data)
    @sessaos_dia = []
    @sessaos = psicologo.sessaos
    @sessaos.each do |sec|
      data_sessao = sec.data.strftime("%Y-%m-%d")
      if data_sessao == data
        @sessaos_dia.push(sec)
      end

    end
    @sessaos_dia.sort{ |a, b| a.hora <=> b.hora }
    return @sessaos_dia
  end

  def buscar_paciente(id)
    @pacientes = @psicologo.pacientes

    @pacientes.each do |pacien|
      if pacien.id == id
        return pacien
      end
    end
    return
  end

  # PATCH/PUT /psicologos/1
  # PATCH/PUT /psicologos/1.json
  def update
    return unless @psicologo.id == session[:user_id]

    respond_to do |format|
      psicologo_params = params.require(:psicologo).permit(:crp, :nome, :password)
      if @psicologo.update(psicologo_params)
        format.html { redirect_to "/psicologos/#{@psicologo.id}", notice: 'Psicologo was successfully updated.' }
        format.json { render :show, status: :ok, location: @psicologo }
      else
        format.html { render :edit }
        format.json { render json: @psicologo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /psicologos/1
  # DELETE /psicologos/1.json
  def destroy
    return unless @psicologo.id == session[:user_id]

    @psicologo.destroy
    redirect_to '/landing'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_psicologo
      @psicologo = Psicologo.find(params[:id])
    end

end

app/helpers/psicologos_helper.rb
module PsicologosHelper
end

app/views/psicologos/create.html.erb
<h1>Psicologos#create</h1>
<p>Find me in app/views/psicologos/create.html.erb</p>

app/views/psicologos/edit.html.erb
<h1>Editing Psicologo</h1>

<%= form_for @psicologo do |f|%>
   <% if @psicologo.errors.any? %>
    <div id="error_explanation">
      <h2>Não foi possível atualizar sua conta:</h2>

      <ul>
        <% @psicologo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div> 
    <%= f.label :crp%>
    <%= f.text_field :crp, id:"crp"%><br>
  </div>
  <div> 
    <%= f.label :nome%>
    <%= f.text_field :nome, id:"nome"%><br>
  </div>
  <div> 
    <%= f.label :senha%>
    <%= f.password_field :password, id:"password"%><br>
  </div>

  <%= f.submit "Atualizar", id:"editar" %>
<%end%>

<%= link_to 'Mostrar', @psicologo %> |
<%= link_to 'Voltar', agenda_psicologo_path(@psicologo.id) %>

app/views/psicologos/main.html.erb
<%= stylesheet_link_tag "psicologos" %>
<h1>AGENDA PSICOLOGIA</h1>

<%= link_to 'Listagem de pacientes', psicologo_pacientes_path(usuario_atual) %>
<br>
<%= link_to 'Listagem de sessões', psicologo_sessaos_path(usuario_atual) %>

<h1>Agenda</h1>
<%= form_tag agenda_psicologo_path(usuario_atual), :method => 'get' do %>
  <p>
    <%= date_field_tag :search, params[:search] %>
    <%= submit_tag "Buscar", id: "botao-buscar" %>
  </p>
<% end %>

<p>
  <% if !@sessaos_dia.nil? and !@sessaos_dia.empty? %>
  <table border="1">
    <thead>
    <tr>
      <th>Data</th>
      <th>Hora</th>
      <th>Paciente</th>
      </th>
    </tr>
    </thead>
    <tbody>
    <% @sessaos_dia.each do |sessao| %>
      <tr>
        <td><%= (sessao.data).strftime("%d/%m/%Y") %></td>
        <td><%= (sessao.hora).strftime("%H:%M") %></td>
        <td><%= buscar_paciente(sessao.paciente_id).nome %></td>
        <td><%= link_to 'Mostrar', psicologo_sessao_path(@psicologo, sessao) %></td>
        <td><%= link_to 'Editar', edit_psicologo_sessao_path(@psicologo, sessao)%></td>
        <td><%= link_to 'Deletar', [@psicologo, sessao], method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
      <%= %>
    <% end %>
    </tbody>
  </table>
<% end %>
</p>

app/views/psicologos/new.html.erb
<h1>Criar conta</h1>
<%= form_for @psicologo do |f|%>
   <% if @psicologo.errors.any? %>
    <div id="error_explanation">
      <h2>Não foi possível cadastradar sua conta:</h2>

      <ul>
        <% @psicologo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div> 
    <%= f.label :crp%>
    <%= f.text_field :crp, id:"crp"%><br>
  </div>
  <div> 
    <%= f.label :nome%>
    <%= f.text_field :nome, id:"nome"%><br>
  </div>
  <div> 
    <%= f.label :senha%>
    <%= f.password_field :password, id:"password"%><br>
  </div>

  <%= f.submit id="criar" %>
<%end%>
<%= link_to 'Voltar', landing_path %>

app/views/psicologos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @psicologo.nome %>
</p>

<p>
  <strong>CRP:</strong>
  <%= @psicologo.crp %>
</p>


<%= link_to 'Editar', edit_psicologo_url(@psicologo), id:"edit" %> |
<%= link_to 'Remover conta', @psicologo, id:"delete", method: :delete, data: { confirm: 'Are you sure?' } %> 
<br>
<%= link_to 'Voltar', agenda_psicologo_path(@psicologo.id) %>