config/routes.rb
Rails.application.routes.draw do

  resources :psicologos do
    member do
      get 'agenda', to: 'psicologos#main'
    end
    resources :pacientes
    resources :sessaos
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'landing', to: 'sessions#landing'
  delete 'logout', to: 'sessions#destroy'
  root 'sessions#landing'

end

app/models/sessao.rb
class Sessao < ApplicationRecord
  belongs_to :paciente
  belongs_to :psicologo
  validates :data, presence: true
  validates :hora, presence: true
  validates :paciente_id, presence: true
  validate :validar_data_hora

  private 
    def validar_data_hora  
      data_hoje = Time.zone.today
      if data < data_hoje
        errors.add(:data, "tem que ser a presente ou futura")
      else
        if(data == data_hoje)
          hora_atual = Time.now
          hora_invalida = hora.hour < hora_atual.hour
          minuto_invalido = hora.hour == hora_atual.hour and hora.min < hora_atual.min
          if (hora_invalida or minuto_invalido)
            errors.add(:hora, "tem que ser a presente ou futura")
          end
        end
      end
    end
end

app/controllers/sessaos_controller.rb
class SessaosController < ApplicationController
  before_action :get_psicologo
  before_action :set_sessao, only: [:show, :edit, :update, :destroy]
  #before_action :set_pacientes, only: [:create, :edit]
  helper_method :usuario_autorizado?
  helper_method :buscar_paciente


  # GET /sessaos
  # GET /sessaos.json
  def index
    @sessaos = @psicologo.sessaos
      unless @sessaos[0].nil?
        eh_psicologo_logado = @sessaos[0].psicologo_id == session[:user_id]
        unless eh_psicologo_logado
          redirect_to agenda_psicologo_path(usuario_atual)
        end
      end


  end

  # GET /sessaos/1
  # GET /sessaos/1.json
  def show
    redirect_to agenda_psicologo_path(usuario_atual) unless usuario_autorizado?
    return
  end

  # GET /sessaos/new
  def new
    @sessao = @psicologo.sessaos.build
  end

  # GET /sessaos/1/edit
  def edit
    redirect_to agenda_psicologo_path(usuario_atual) unless usuario_autorizado?
    return
  end

  # POST /sessaos
  # POST /sessaos.json
  def create
    @sessao = @psicologo.sessaos.build(sessao_params)

    respond_to do |format|
      if @sessao.save
        format.html { redirect_to psicologo_sessaos_path(@psicologo, @sessao), notice: 'Sessao was successfully created.' }
        format.json { render :show, status: :created, location: @sessao }
      else
        format.html { render :new }
        format.json { render json: @sessao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sessaos/1
  # PATCH/PUT /sessaos/1.json
  def update
    return unless usuario_autorizado?

    respond_to do |format|
      if @sessao.update(sessao_params)
        format.html { redirect_to psicologo_sessaos_path(@psicologo), notice: 'Sessao was successfully updated.' }
        format.json { render :show, status: :ok, location: @sessao }
      else
        format.html { render :edit }
        format.json { render json: @sessao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sessaos/1
  # DELETE /sessaos/1.json
  def destroy
    return unless usuario_autorizado?

    @sessao.destroy
    respond_to do |format|
      format.html { redirect_to psicologo_sessaos_path(@psicologo), notice: 'Sessao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sessao
      @sessao = @psicologo.sessaos.find(params[:id])
    end

    def get_psicologo
      @psicologo = Psicologo.find(params[:psicologo_id])
    end

    def get_paciente
      @paciente = @psicologo.paciente.find(params[:paciente_id])
    end
    # Only allow a list of trusted parameters through.
    def sessao_params
      params.require(:sessao).permit(:data, :hora, :paciente_id)
    end

    def usuario_autorizado?
      @sessao.psicologo_id == session[:user_id]
    end

    def set_pacientes
      @pacientes = @psicologo.pacientes
    end

    def buscar_paciente(id)
      @pacientes = @psicologo.pacientes

      @pacientes.each do |pacien|
        if pacien.id == id
          return pacien
        end
      end
      return
    end


end

app/helpers/sessaos_helper.rb
module SessaosHelper
end

app/views/sessaos/_form.html.erb
<%= form_with(model: [@psicologo, sessao], local: true) do |form| %>
  <% if sessao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sessao.errors.count, "error") %> prohibited this sessao from being saved:</h2>

      <ul>
        <% sessao.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_select :data %>
  </div>

  <div class="field">
    <%= form.label :hora %>
    <%= form.time_select :hora %>
  </div>

  <div class="field">
    <%= form.label :paciente_id %>
    <%= form.collection_select(:paciente_id, @psicologo.pacientes, :id, :nome, include_blank: true) %>
  </div>

  <div class="actions">
    <%= form.submit "Cadastrar", id: "cadastrar-sessao" %>
  </div>
<% end %>

app/views/sessaos/edit.html.erb
<h1>Editing Sessao</h1>

<%= render 'form', sessao: @sessao %>

<%= link_to 'Mostrar', [@psicologo, @sessao] %> |
<%= link_to 'Voltar', psicologo_sessaos_path(@psicologo) %>

app/views/sessaos/index.html.erb
<%= stylesheet_link_tag "sessaos" %>
<p id="notice"><%= notice %></p>

<h1>Sessaos</h1>
<% if !@psicologo.sessaos.empty? %>
<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Hora</th>
      <th>Paciente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sessaos.each do |sessao| %>
      <tr>
        <td><%= (sessao.data).strftime("%d/%m/%Y") %></td>
        <td><%= (sessao.hora).strftime("%H:%M") %></td>
        <td><%= buscar_paciente(sessao.paciente_id).nome %></td>
        <td><%= link_to 'Mostrar', psicologo_sessao_path(@psicologo, sessao)%></td>
        <td><%= link_to 'Editar', edit_psicologo_sessao_path(@psicologo, sessao)%></td>
        <td><%= link_to 'Deletar', [@psicologo, sessao], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Voltar', agenda_psicologo_path(usuario_atual) %></td>
      </tr>
      <%= %>
    <% end %>
  </tbody>
</table>
<%end %>
<br>

<%= link_to 'Criar Nova Sessao', new_psicologo_sessao_path %>
<br>
<%= link_to 'Voltar', agenda_psicologo_path(usuario_atual) %>

app/views/sessaos/new.html.erb
<h1>New Sessao</h1>

<%= render 'form', sessao: @sessao %>

<%= link_to 'Voltar', psicologo_sessaos_path(@psicologo) %>

app/views/sessaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= (@sessao.data).strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Hora:</strong>
  <%= (@sessao.hora).strftime("%H:%M") %>
</p>

<p>
  <strong>Paciente:</strong>
  <%= buscar_paciente( @sessao.paciente_id ).nome %>
</p>

<% if usuario_atual != nil %>
  <%= link_to 'Editar', edit_psicologo_sessao_path(@psicologo, @sessao), id: "edit" %> |
  <%= link_to 'Deletar', [@psicologo, @sessao], id:"delete", method: :delete, data: { confirm: 'Are you sure?' } %> |

<% end %>
<%= link_to 'Voltar', psicologo_sessaos_path(@psicologo) %>